import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

/**
 * One operator-panel button: the actuator it drives and the words on it.
 *
 * The panel clock domain and the GUI are generated from the same table, so a
 * button can never name an actuator the plant does not have.
 *
 * GENERATED by tools/actuators.py - edit the table there, not this file.
 */
public final class ManualActuator {

	public final String id;
	public final String machine;
	public final String label;

	private ManualActuator(String id, String machine, String label) {
		this.id = id;
		this.machine = machine;
		this.label = label;
	}

	private static final ManualActuator[] ALL = {
		new ManualActuator("bl.vacOn", "Bottle loader", "Vacuum on"),
		new ManualActuator("bl.release", "Bottle loader", "Release"),
		new ManualActuator("bl.armSource", "Bottle loader", "Arm to supply"),
		new ManualActuator("bl.armDest", "Bottle loader", "Arm to conveyor"),
		new ManualActuator("cv.motInfeed", "Conveyor", "Infeed belt"),
		new ManualActuator("cv.takeFromPos1", "Conveyor", "Lift off position 1"),
		new ManualActuator("cv.motOutfeed", "Conveyor", "Outfeed belt"),
		new ManualActuator("cv.injectInfeed", "Conveyor", "Set bottle on infeed"),
		new ManualActuator("cv.injectOutfeed", "Conveyor", "Set bottle on outfeed"),
		new ManualActuator("cv.collectFromEnd", "Conveyor", "Take off at the end"),
		new ManualActuator("rt.rotaryTrigger", "Rotary table", "Index 60 degrees"),
		new ManualActuator("rt.loadPos1", "Rotary table", "Place at position 1"),
		new ManualActuator("rt.unloadExit", "Rotary table", "Unload position 6"),
		new ManualActuator("f1.valveOpen", "Filler 1", "Valve open"),
		new ManualActuator("f2.valveOpen", "Filler 2", "Valve open"),
		new ManualActuator("ll.pusherExtend", "Lid loader", "Magazine pusher"),
		new ManualActuator("ll.vacOn", "Lid loader", "Vacuum on"),
		new ManualActuator("ll.armSource", "Lid loader", "Arm to pick-up"),
		new ManualActuator("ll.armDest", "Lid loader", "Arm to bottle"),
		new ManualActuator("ll.refill", "Lid loader", "Refill magazine"),
		new ManualActuator("cp.screwOn", "Capper", "Screw down"),
		new ManualActuator("lb.applyLabelExtend", "Labeller", "Applicator out"),
		new ManualActuator("lb.applyLabelRetract", "Labeller", "Applicator back"),
		new ManualActuator("lb.rollerOnOff", "Labeller", "Glue roller"),
		new ManualActuator("sp.diverterExtend", "Quality splitter", "Diverter to reject"),
		new ManualActuator("sp.diverterRetract", "Quality splitter", "Diverter to normal"),
		new ManualActuator("sp.admitBottle", "Quality splitter", "Admit from outfeed"),
		new ManualActuator("rc.recyclingConveyorMotor", "Recycling conveyor", "Belt"),
		new ManualActuator("rc.injectAtEntry", "Recycling conveyor", "Set bottle at entry"),
		new ManualActuator("rc.collectAtReturn", "Recycling conveyor", "Take off at return"),
		new ManualActuator("lr.cylZaxisExtend", "Lid removal", "Head down"),
		new ManualActuator("lr.unscrewTurnExtend", "Lid removal", "Untwist"),
		new ManualActuator("lr.unscrewTurnRetract", "Lid removal", "Twist back"),
		new ManualActuator("lr.lidGripperExtend", "Lid removal", "Gripper close"),
		new ManualActuator("lr.lidEjectExtend", "Lid removal", "Eject lid"),
		new ManualActuator("ld.cylClampBottleExtend", "Liquid dumper", "Clamp bottle"),
		new ManualActuator("ld.invertRotateExtend", "Liquid dumper", "Invert"),
		new ManualActuator("ld.invertRotateRetract", "Liquid dumper", "Upright"),
		new ManualActuator("ld.drainValveOnOff", "Liquid dumper", "Drain valve"),
		new ManualActuator("br.motorOnOff", "Bottle return", "Collector belt"),
		new ManualActuator("br.transferArmExtend", "Bottle return", "Transfer arm out"),
		new ManualActuator("br.transferArmRetract", "Bottle return", "Transfer arm back")
	};

	public static List<ManualActuator> all() {
		List<ManualActuator> list = new ArrayList<ManualActuator>();
		for (ManualActuator a : ALL) {
			list.add(a);
		}
		return Collections.unmodifiableList(list);
	}

	/** Machine labels in plant order, for grouping the panel. */
	public static List<String> machines() {
		List<String> names = new ArrayList<String>();
		for (ManualActuator a : ALL) {
			if (!names.contains(a.machine)) {
				names.add(a.machine);
			}
		}
		return Collections.unmodifiableList(names);
	}

	public String toString() {
		return machine + " / " + label;
	}
}
